version: 2
update_submodule: &update_submodule
  name: Update Submodule
  command: |
    git submodule sync
    git submodule update --recursive --init

jobs:
  run_torchhub:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: gpu.small
    steps:
      - checkout
      - run:
          name: Setup CI environment
          command: ./scripts/setup_ci.sh
      - run:
          name: Install Deps
          command: ./scripts/install_basics.sh; ./scripts/install.sh
      - run:
          name: Sanity Check
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python scripts/sanity_check.py
      - run:
          name: Run Pytorch scripts
          command: ./scripts/run_pytorch.sh
          no_output_timeout: 1h

  run_training_suite:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: gpu.small
    steps:
      - checkout
      - run:
          <<: *update_submodule
      - run:
          name: Setup CI environment
          command: ./scripts/setup_ci.sh
      - run:
          name: Install Conda
          command: ./scripts/install_basics.sh
      - run:
          name: Install PyTorch nightly
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; conda install -y pytorch -c pytorch-nightly
      - run:
          name: Validate training benchmark suite
          command: . ~/miniconda3/etc/profile.d/conda.sh; conda activate base; python benchmark/test.py

workflows:
  version: 2
  workflow-build:
    jobs:
      - run_torchhub
      - run_training_suite
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_torchhub
      - run_training_suite
